### ISSUE TITLE
Unable to perform delete operation

### ISSUE THREAD

**Issue by nareshr8** [Azure/azure-documentdb-rxjava#15]
When I try to delete, I am getting the following logs:
`
java.lang.IllegalArgumentException: port out of range:-1
	at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143) ~[na:1.8.0_25]
	at java.net.InetSocketAddress.createUnresolved(InetSocketAddress.java:254) ~[na:1.8.0_25]
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:126) ~[netty-transport-4.1.7.Final.jar:4.1.7.Final]
	at io.reactivex.netty.client.ClientChannelFactoryImpl.connect(ClientChannelFactoryImpl.java:61) ~[rxnetty-0.4.20.jar:0.4.20]
	at io.reactivex.netty.client.ConnectionPoolImpl.performAquire(ConnectionPoolImpl.java:171) ~[rxnetty-0.4.20.jar:0.4.20]
	at io.reactivex.netty.client.ConnectionPoolImpl.access$300(ConnectionPoolImpl.java:45) ~[rxnetty-0.4.20.jar:0.4.20]
	at io.reactivex.netty.client.ConnectionPoolImpl$1.call(ConnectionPoolImpl.java:139) ~[rxnetty-0.4.20.jar:0.4.20]
	at io.reactivex.netty.client.ConnectionPoolImpl$1.call(ConnectionPoolImpl.java:124) ~[rxnetty-0.4.20.jar:0.4.20]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) [rxjava-1.2.5.jar:1.2.5]
	at rx.Observable.unsafeSubscribe(Observable.java:10144) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) [rxjava-1.2.5.jar:1.2.5]
	at rx.Observable.unsafeSubscribe(Observable.java:10144) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) [rxjava-1.2.5.jar:1.2.5]
	at rx.Observable.unsafeSubscribe(Observable.java:10144) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) [rxjava-1.2.5.jar:1.2.5]
	at rx.Observable.unsafeSubscribe(Observable.java:10144) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) [rxjava-1.2.5.jar:1.2.5]
	at rx.Observable.unsafeSubscribe(Observable.java:10144) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) [rxjava-1.2.5.jar:1.2.5]
	at rx.Observable.subscribe(Observable.java:10240) [rxjava-1.2.5.jar:1.2.5]
	at rx.Observable.subscribe(Observable.java:10207) [rxjava-1.2.5.jar:1.2.5]
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:444) [rxjava-1.2.5.jar:1.2.5]
	at rx.observables.BlockingObservable.single(BlockingObservable.java:341) [rxjava-1.2.5.jar:1.2.5]
	at com.microsoft.azure.documentdb.BridgeInternal$2.getDatabaseAccountFromEndpoint(BridgeInternal.java:95) ~[azure-documentdb-rx-0.9.0-rc2.jar:na]
	at com.microsoft.azure.documentdb.GlobalEndpointManager.getDatabaseAccountFromAnyEndpoint(GlobalEndpointManager.java:121) ~[azure-documentdb-1.13.0.jar:na]
	at com.microsoft.azure.documentdb.GlobalEndpointManager.refreshEndpointListInternal(GlobalEndpointManager.java:155) ~[azure-documentdb-1.13.0.jar:na]
	at com.microsoft.azure.documentdb.GlobalEndpointManager.initialize(GlobalEndpointManager.java:148) ~[azure-documentdb-1.13.0.jar:na]
	at com.microsoft.azure.documentdb.GlobalEndpointManager.getReadEndpoint(GlobalEndpointManager.java:81) ~[azure-documentdb-1.13.0.jar:na]
	at com.microsoft.azure.documentdb.GlobalEndpointManager.resolveServiceEndpoint(GlobalEndpointManager.java:93) ~[azure-documentdb-1.13.0.jar:na]
	at com.microsoft.azure.documentdb.rx.internal.RxGatewayStoreModel.getUri(RxGatewayStoreModel.java:214) ~[azure-documentdb-rx-0.9.0-rc2.jar:na]
	at com.microsoft.azure.documentdb.rx.internal.RxGatewayStoreModel.performRequest(RxGatewayStoreModel.java:165) ~[azure-documentdb-rx-0.9.0-rc2.jar:na]
	at com.microsoft.azure.documentdb.rx.internal.RxGatewayStoreModel.doRead(RxGatewayStoreModel.java:119) ~[azure-documentdb-rx-0.9.0-rc2.jar:na]
	at com.microsoft.azure.documentdb.rx.internal.RxGatewayStoreModel.processMessage(RxGatewayStoreModel.java:383) ~[azure-documentdb-rx-0.9.0-rc2.jar:na]
	at com.microsoft.azure.documentdb.rx.internal.RxDocumentClientImpl.lambda$doRead$17(RxDocumentClientImpl.java:440) [azure-documentdb-rx-0.9.0-rc2.jar:na]
	at com.microsoft.azure.documentdb.rx.internal.RxDocumentClientImpl$$Lambda$18/170067997.call(Unknown Source) ~[na:na]
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35) [rxjava-1.2.5.jar:1.2.5]
	at rx.Observable.unsafeSubscribe(Observable.java:10144) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeRedo$2.call(OnSubscribeRedo.java:273) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeRedo$5.request(OnSubscribeRedo.java:361) [rxjava-1.2.5.jar:1.2.5]
	at rx.Subscriber.setProducer(Subscriber.java:211) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:353) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:47) [rxjava-1.2.5.jar:1.2.5]
	at rx.Observable.unsafeSubscribe(Observable.java:10144) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53) [rxjava-1.2.5.jar:1.2.5]
	at com.microsoft.azure.documentdb.rx.internal.RxDocumentClientImpl.lambda$createPutMoreContentObservable$26(RxDocumentClientImpl.java:682) [azure-documentdb-rx-0.9.0-rc2.jar:na]
	at com.microsoft.azure.documentdb.rx.internal.RxDocumentClientImpl$$Lambda$19/1881124608.call(Unknown Source) [azure-documentdb-rx-0.9.0-rc2.jar:na]
	at rx.Observable.unsafeSubscribe(Observable.java:10144) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OperatorSubscribeOn.call(OperatorSubscribeOn.java:45) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OperatorSubscribeOn.call(OperatorSubscribeOn.java:30) [rxjava-1.2.5.jar:1.2.5]
	at rx.Observable.unsafeSubscribe(Observable.java:10144) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) [rxjava-1.2.5.jar:1.2.5]
	at rx.Observable.unsafeSubscribe(Observable.java:10144) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) [rxjava-1.2.5.jar:1.2.5]
	at rx.Observable.unsafeSubscribe(Observable.java:10144) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) [rxjava-1.2.5.jar:1.2.5]
	at rx.Observable.unsafeSubscribe(Observable.java:10144) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) [rxjava-1.2.5.jar:1.2.5]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) [rxjava-1.2.5.jar:1.2.5]
	at rx.Observable.subscribe(Observable.java:10240) [rxjava-1.2.5.jar:1.2.5]
	at rx.Observable.subscribe(Observable.java:10207) [rxjava-1.2.5.jar:1.2.5]
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:444) [rxjava-1.2.5.jar:1.2.5]
	at rx.observables.BlockingObservable.single(BlockingObservable.java:341) [rxjava-1.2.5.jar:1.2.5]
	at com.microsoft.azure.documentdb.BridgeInternal$1.readCollection(BridgeInternal.java:74) [azure-documentdb-rx-0.9.0-rc2.jar:na]
	at com.microsoft.azure.documentdb.internal.routing.ClientCollectionCache.readCollection(ClientCollectionCache.java:33) [azure-documentdb-1.13.0.jar:na]
	at com.microsoft.azure.documentdb.internal.routing.ClientCollectionCache.getByRid(ClientCollectionCache.java:26) [azure-documentdb-1.13.0.jar:na]
	at com.microsoft.azure.documentdb.internal.routing.CollectionCache$3.call(CollectionCache.java:119) [azure-documentdb-1.13.0.jar:na]
	at com.microsoft.azure.documentdb.internal.routing.CollectionCache$3.call(CollectionCache.java:116) [azure-documentdb-1.13.0.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_25]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
`

**Comment by moderakh** [comment]
Which connection mode are you using GateWay or Direct?

Also the following line suggests that you are not passing the port as part of your endpoint:
java.lang.IllegalArgumentException: port out of range:-1 at 

Please make sure you are passing port number (443) as your endpoint:
use `https://{xxx}.documents.azure.com:443` instead of `https://{xxx}.documents.azure.com`

**Comment by nareshr8** [comment]
Thanks. It worked. Since select worked without port, I thought this should also work.
